### ISSUE TITLE
[KED-2027] Missing dependancies in spaceflights tutorial

### ISSUE THREAD

**Issue by nakhan98** [quantumblacklabs/kedro-examples#58]
## Description
The following python libraries required by the kedro spaceflights tutorial are missing from `requirements.txt`:
- pandas
- xlrd

## Context
Cannot run the completed spaceflights tutorial without manually installing the above two libraries from `pip`.

## Steps to Reproduce

1. Create a fresh conda environment (python 3.7.7): `conda create --name=argo python=3.7 -y`
2. Install kedro: `pip install kedro`
3. `cd` into `kedro-tutorial`
4. Run `kedro install`
5. Run `kedro run`

## Expected Result
I expect the pipeline to run and complete succesfully.

## Actual Result
- Get the following traceback:

```
$ kedro run
/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/context/__init__.py:46: DeprecationWarning: All the modules in `kedro.context` have been moved to `kedro.framework.context`, and `kedro.context` will be removed in Kedro 0.17.0. Please update import paths from `kedro.context` to `kedro.framework.context` in your Kedro project.
  DeprecationWarning,
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/argo/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 725, in main
    cli_collection()
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/nasef_khan/dev/kedro-examples/kedro-tutorial/kedro_cli.py", line 221, in run
    context = load_context(Path.cwd(), env=env, extra_params=params)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/framework/context/context.py", line 886, in load_context
    context_class = load_obj(context_path)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/utils.py", line 53, in load_obj
    module_obj = importlib.import_module(obj_path)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/nasef_khan/dev/kedro-examples/kedro-tutorial/src/kedro_tutorial/run.py", line 36, in <module>
    from kedro_tutorial.pipeline import create_pipelines
  File "/Users/nasef_khan/dev/kedro-examples/kedro-tutorial/src/kedro_tutorial/pipeline.py", line 32, in <module>
    from .pipelines.data_science import pipeline as ds
  File "/Users/nasef_khan/dev/kedro-examples/kedro-tutorial/src/kedro_tutorial/pipelines/data_science/pipeline.py", line 30, in <module>
    from .nodes import evaluate_model, split_data, train_model
  File "/Users/nasef_khan/dev/kedro-examples/kedro-tutorial/src/kedro_tutorial/pipelines/data_science/nodes.py", line 33, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

- After doing a `pip install pandas` and re-running `kedro run` I get the following:
```
$ kedro run
/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/context/__init__.py:46: DeprecationWarning: All the modules in `kedro.context` have been moved to `kedro.framework.context`, and `kedro.context` will be removed in Kedro 0.17.0. Please update import paths from `kedro.context` to `kedro.framework.context` in your Kedro project.
  DeprecationWarning,
/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:8: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/_pytest/mark/structures.py:443: DeprecationWarning: The usage of `cmp` is deprecated and will be removed on or after 2021-06-01.  Please use `eq` and `order` instead.
  @attr.s(cmp=False, hash=False)
2020-08-27 02:29:46,336 - root - INFO - ** Kedro project kedro-tutorial
/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/fsspec/implementations/local.py:33: FutureWarning: The default value of auto_mkdir=True has been deprecated and will be changed to auto_mkdir=False by default in a future release.
  FutureWarning,
2020-08-27 02:29:46,474 - kedro.io.data_catalog - INFO - Loading data from `companies` (CSVDataSet)...
2020-08-27 02:29:46,533 - kedro.pipeline.node - INFO - Running node: preprocessing_companies: preprocess_companies([companies]) -> [preprocessed_companies]
2020-08-27 02:29:46,584 - kedro_tutorial.pipelines.data_engineering.nodes - INFO - Running 'preprocess_companies' took 0.05 seconds
2020-08-27 02:29:46,584 - kedro_tutorial.pipelines.data_engineering.nodes - INFO - Running 'preprocess_companies' took 0.05 seconds
2020-08-27 02:29:46,585 - kedro.io.data_catalog - INFO - Saving data to `preprocessed_companies` (CSVDataSet)...
2020-08-27 02:29:46,864 - kedro.runner.sequential_runner - INFO - Completed 1 out of 6 tasks
2020-08-27 02:29:46,864 - kedro.io.data_catalog - INFO - Loading data from `shuttles` (ExcelLocalDataSet)...
2020-08-27 02:29:46,866 - kedro.runner.sequential_runner - WARNING - There are 5 nodes that have not run.
You can resume the pipeline run by adding the following argument to your previous command:
  --from-nodes "preprocessing_shuttles,create_master_table([preprocessed_companies,preprocessed_shuttles,reviews]) -> [master_table],split_data([master_table,parameters]) -> [X_test,X_train,y_test,y_train]"
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/io/core.py", line 213, in load
    return self._load()
  File "/Users/nasef_khan/dev/kedro-examples/kedro-tutorial/src/kedro_tutorial/io/xls_local.py", line 87, in _load
    return pd.read_excel(self._filepath, **self._load_args)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py", line 21, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/pandas/compat/_optional.py", line 93, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/argo/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 725, in main
    cli_collection()
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/nasef_khan/dev/kedro-examples/kedro-tutorial/kedro_cli.py", line 230, in run
    pipeline_name=pipeline,
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/framework/context/context.py", line 737, in run
    raise error
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/framework/context/context.py", line 729, in run
    run_result = runner.run(filtered_pipeline, catalog, run_id)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/runner/runner.py", line 101, in run
    self._run(pipeline, catalog, run_id)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/runner/sequential_runner.py", line 90, in _run
    run_node(node, catalog, self._is_async, run_id)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/runner/runner.py", line 213, in run_node
    node = _run_node_sequential(node, catalog, run_id)
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/runner/runner.py", line 221, in _run_node_sequential
    inputs = {name: catalog.load(name) for name in node.inputs}
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/runner/runner.py", line 221, in <dictcomp>
    inputs = {name: catalog.load(name) for name in node.inputs}
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/io/data_catalog.py", line 393, in load
    result = func()
  File "/usr/local/anaconda3/envs/argo/lib/python3.7/site-packages/kedro/io/core.py", line 222, in load
    raise DataSetError(message) from exc
kedro.io.core.DataSetError: Failed while loading data from data set ExcelLocalDataSet(engine=xlsxwriter, filepath=/Users/nasef_khan/dev/kedro-examples/kedro-tutorial/data/01_raw/shuttles.xlsx, load_args={'engine': xlrd}, save_args={}).
Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
```

- After installing `xlrd` throough pip, the pipeline runs cleanly without error.

## Your Environment
Include as many relevant details about the environment you experienced the bug in:

* Kedro-Example: Latest spaceflights tutorial
* Kedro version used (`pip show kedro` or `kedro -V`):
```
$ pip show kedro
Name: kedro
Version: 0.16.4
Summary: Kedro helps you build production-ready data and analytics pipelines
Home-page: https://github.com/quantumblacklabs/kedro
Author: QuantumBlack Labs
Author-email: None
License: Apache Software License (Apache 2.0)
Location: /usr/local/anaconda3/envs/argo/lib/python3.7/site-packages
Requires: toposort, PyYAML, python-json-logger, setuptools, jupyter-client, click, anyconfig, cookiecutter, cachetools, jmespath, fsspec, pip-tools, pluggy
Required-by: kedro-viz
```
* Python version used (`python -V`):
Python version:
```
$ python -V
Python 3.7.7
```

Conda info:
```
$ conda info

     active environment : argo
    active env location : /usr/local/anaconda3/envs/argo
            shell level : 2
       user config file : /Users/nasef_khan/.condarc
 populated config files : /Users/nasef_khan/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __osx=10.15.6
       base environment : /usr/local/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/anaconda3/pkgs
                          /Users/nasef_khan/.conda/pkgs
       envs directories : /usr/local/anaconda3/envs
                          /Users/nasef_khan/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.8.3 Darwin/19.6.0 OSX/10.15.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
* Operating system and version: 
```
Darwin/19.6.0 OSX/10.15.6
```

**Comment by MerelTheisenQB** [comment]
Thanks for flagging this @nakhan98! I've created a ticket to fix it.

**Comment by yetudada** [comment]
We've fixed this and the repo has been moved to [`kedro-training`](https://github.com/quantumblacklabs/kedro-training)
